// Named constants for AuditLog.action / AdminAction.action so event names
// stay consistent across the codebase instead of being retyped as free
// strings at each call site. This is intentionally an extensible list, not
// an enum/migration — new event names can be added here without a schema
// change.
export const AuditEvent = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_CREATED: 'USER_CREATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_APPROVED: 'DEPOSIT_APPROVED',
  DEPOSIT_REJECTED: 'DEPOSIT_REJECTED',
  WITHDRAWAL_CREATED: 'WITHDRAWAL_CREATED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  FINANCIAL_ADJUSTMENT: 'FINANCIAL_ADJUSTMENT',
  TRADING_PAUSED: 'TRADING_PAUSED',
  TRADING_RESUMED: 'TRADING_RESUMED',
  DEPOSITS_PAUSED: 'DEPOSITS_PAUSED',
  DEPOSITS_RESUMED: 'DEPOSITS_RESUMED',
  WITHDRAWALS_PAUSED: 'WITHDRAWALS_PAUSED',
  WITHDRAWALS_RESUMED: 'WITHDRAWALS_RESUMED',
  REGISTRATIONS_PAUSED: 'REGISTRATIONS_PAUSED',
  REGISTRATIONS_RESUMED: 'REGISTRATIONS_RESUMED',
  MARKET_DISABLED: 'MARKET_DISABLED',
  MARKET_ENABLED: 'MARKET_ENABLED',
  SECURITY_SETTING_CHANGED: 'SECURITY_SETTING_CHANGED',

  // ---- CMS (Phase 3) --------------------------------------------------------
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_UPDATED: 'CONTENT_UPDATED',
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  CONTENT_UNPUBLISHED: 'CONTENT_UNPUBLISHED',
  CONTENT_ARCHIVED: 'CONTENT_ARCHIVED',
  CONTENT_RESTORED: 'CONTENT_RESTORED',
  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  MEDIA_DELETED: 'MEDIA_DELETED',
  NAVIGATION_UPDATED: 'NAVIGATION_UPDATED',

  // ---- Customer Support (Phase 3) --------------------------------------------
  // Ordinary customer messages are NOT audited here — that's normal support
  // conversation history, stored in SupportMessage, not a security/compliance
  // event. Only administrative actions on tickets are.
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_STATUS_CHANGED: 'TICKET_STATUS_CHANGED',
  TICKET_PRIORITY_CHANGED: 'TICKET_PRIORITY_CHANGED',
  INTERNAL_NOTE_CREATED: 'INTERNAL_NOTE_CREATED',
  SUPPORT_CATEGORY_CHANGED: 'SUPPORT_CATEGORY_CHANGED',
} as const

export type AuditEventName = (typeof AuditEvent)[keyof typeof AuditEvent]
